# Cryptohack Lattices What's a Lattice?

"""
We're now ready to start talking about lattices. Given a set of linearly independent vectors v_1, v_2, ..., v_n ∈ R^m, the lattice L 
generated by v_1, v_2, ..., v_n is the set of linearly independent vectors v_1, v_2, ..., v_n with integer coefficients

L = a_1 * v_1 + a_2 * v_2 + ... + a_k * v_k : a_1, a_2, ..., a_n ∈ Z

The basis for the lattice L is any set of independent vectors that generates L. The choice of basis is far from unique. In the image below, we show a two dimensional lattice with teo different basis vectors given by u_1, u_2 and v_1, v_2.

Using a basis, we can reach any point within the lattice with integer multiples of thebasis vectors. The basis vectors also define the fundamental domain:

F(v_1, ..., v_n) = t_1v_1 + t_2v_2 + ... + t_nv_n : 0 ≤ t_i < 1

As a two dimensional example, the fundamental domain is the parallelogram with sides u_1 and u_2

We can calcualte the volume of the fundamental domain from the basis vectors. As an example, let us take a two dimensional lattice with basis vectors v = (2,5), u = (3,1) 

Create a matrix A with rows corresponding to the basis vectors:

A = [[2,5],[3,1]]

The volume of the fundamental domain is the magnitude of the determinant of A:

vol(F) = |det(A)| = |2*1 - 5*3| = |-13| = -13

"""

"""
For the flag, calcualte the volume of the fundamental domain with the basis vectors

v_1 = (6,2,-3)
v_2 = (5,1,4)
v_3 = (2,7,1)

"""

import numpy as np

Matrix = np.array([[6,2,-3], [5,1,4], [2,7,1]])
det = np.linalg.det(Matrix)
print("The flag is: ", det)
